### PR TITLE
Fix use of deprecated express API

### LINKED ISSUE #2: express deprecated
express deprecated res.send(status, body): Use res.status(status).send(body) instead node_modules/server-health/lib/health.js:62:17

### PR DESCRIPTION
**Pull request by irnnr**
Use res.status(status).send(body) instead of res.send(body, status)
Fixes #2

### CODE REVIEW

**Comment by ruudjutinant** [comment]
thank you very much

**Review by ruudjutinant — APPROVED** [review]

**Review by TinOo512 — APPROVED** [review]
lgtm

**Comment by irnnr** [comment]
@TinOo512 I dug a bit deeper and found we needed some more work to properly/fully support express. I've added those changes and tests for express. Can you please have a look at the new changes?

Thx! :)

@ruudjutinant would you mind having a look as well?

File: lib/health.js [hunk 1]
```diff
@@ -55,13 +55,16 @@ module.exports.exposeHealthEndpoint = (server, endpoint = '/health', framework =
...
           .then(({ statusCode, status }) => {
-            res.status(statusCode).send(status);
-            next();
+            res.status(statusCode).json(status);
           })
-          .catch(err => next(err));
+          .catch(err => {
+            const errorCode = err.name.replace('Error', '');
+
+            res.status(err.statusCode).json({ code: errorCode, message: err.message });
```
Comment (TinOo512) [inline lib/health.js]: Hmm I think you can pass the error directly, BaseError (https://github.com/AugustHome/server-health/blob/master/lib/errors/base_error.js#L38) override the toJSON method so I guess when express call `JSON.stringify` we will return the same object? Isn't express using https://github.com/pillarjs/finalhandler#finalhandlerreq-res-options? Because calling `next(err)` should work?

**Review by TinOo512 — CHANGES_REQUESTED** [review]

File: lib/health.js (hunk 1 above)
Comment (irnnr) [reply lib/health.js]: true, that works.

**Review by TinOo512 — APPROVED** [review]

**Comment by ruudjutinant** [comment]
do you have a plan to push this to npm?

**Comment by irnnr** [comment]
yes, just didn't get around to it yet.

**Comment by irnnr** [comment]
@ruudjutinant package is published now
